/**
 * Raw-account decoders for the five client-relevant accounts.
 *
 * Every byte offset below is pinned two ways: against the size-locked Rust
 * layouts (state/*.rs, frozen by their `size_is_exactly_*` tests) and
 * against the committed cross-language fixture
 * `tests/fixtures/account_layouts.json`, generated by Rust's own borsh
 * writer (`state/layout_fixture.rs`) and asserted byte-for-byte in the SDK
 * decoder suite. A struct change cannot pass both sides silently.
 *
 * Decoding rules mirroring the program:
 * - account data is `discriminator (8) ++ borsh struct`, little-endian;
 * - account length is the allocated (InitSpace) size — exact match required,
 *   so a layout change is a loud decode error, never a silent misread;
 * - `Option<Pubkey>` occupies its max slot (tag + 32) regardless of `None`,
 *   so field offsets after it are stable;
 * - all 64-bit integers decode to `BigInt` (see codec.ts).
 */

import { BorshReader } from "./codec";

/** sha256("account:<Name>")[..8] — anchor account discriminators. */
export const ACCOUNT_DISCRIMINATORS: Readonly<Record<string, string>> = {
  GlobalConfig: "95089ccaa0fcb0d9",
  Round: "577fa533494e74ae",
  PlayerEntry: "9e062768ea0499ff",
  PlayerEscrow: "55d845586e9c08aa",
  MegaPotVault: "9a865b9e11cee992",
  RoundVault: "8fa9d220dd7bc777",
  TreasuryVault: "5666136d383a9051",
  EntropyChain: "f861023aae4cfd00",
} as const;

/** Account sizes including the 8-byte discriminator (size-lock tests). */
export const ACCOUNT_SIZES: Readonly<Record<string, number>> = {
  GlobalConfig: 340,
  Round: 302,
  PlayerEntry: 109,
  PlayerEscrow: 122,
  MegaPotVault: 89,
  RoundVault: 33,
  TreasuryVault: 65,
  EntropyChain: 193,
} as const;

/**
 * Byte offset of `Round.entry_count` (u32 LE) — the next deposit's index.
 * Verified against the layout fixture; the value is 65 (disc + round_id +
 * state + 6×i64/u64), NOT 73 — an earlier hand-sum here double-counted
 * `total_lamports` and would have read 4 bytes of `first_depositor`.
 */
export const ROUND_ENTRY_COUNT_OFFSET = 65;

/** `OracleProvider` wire order: 0 = Switchboard, 1 = Orao (never built),
 *  2 = Entropy (the operator hash chain — randomness fallback). */
export type OracleProviderName = "switchboard" | "orao" | "entropy";
export const ORACLE_PROVIDERS: readonly OracleProviderName[] = ["switchboard", "orao", "entropy"];

/** `round_id` sentinel for "no round" in the entropy chain. */
export const ENTROPY_NONE = 0xffff_ffff_ffff_ffffn;

/** `RoundState` wire values (declaration order in state/round.rs). */
export type RoundStateName =
  | "open"
  | "locked"
  | "awaitingRandomness"
  | "settled"
  | "cancelled";

const ROUND_STATES: readonly RoundStateName[] = [
  "open",
  "locked",
  "awaitingRandomness",
  "settled",
  "cancelled",
];

/** `GlobalConfig` as stored at PDA ["config"]. */
export interface GlobalConfigData {
  admin: string;
  /** `null` while no two-step admin transfer is pending. */
  pendingAdmin: string | null;
  treasuryAuthority: string;
  oracleProgramId: string;
  /** Pinned Switchboard On-Demand queue; `commit_randomness` targets it. */
  oracleQueue: string;
  feeBpsAdmin: number;
  feeBpsMega: number;
  winnerBps: number;
  megaAwardBps: number;
  megaTriggerModulus: number;
  maxEntriesPerRound: number;
  roundDurationSecs: bigint;
  maxRoundDurationSecs: bigint;
  antiSnipeWindowSecs: bigint;
  antiSnipeExtensionSecs: bigint;
  claimDeadlineSecs: bigint;
  minDepositLamports: bigint;
  antiSnipeMinDepositLamports: bigint;
  keeperTipLamports: bigint;
  randomnessRevealDeadlineSlots: bigint;
  activeRoundId: bigint;
  nextRoundId: bigint;
  oracleProvider: OracleProviderName;
  paused: boolean;
  bump: number;
  /** Permissionless auto-deposit window (Phase 10); read after `bump`. */
  autoDepositWindowSecs: bigint;
  autoDepositTipLamports: bigint;
  /** Feature kill switch — `false` on the pre-upgrade deployed account. */
  autoDepositEnabled: boolean;
  /** Refund share of a settled pot, bps — the fourth slice (Phase 11). */
  refundBps: number;
  /** Mega-Pot share paid pro-rata to the field on a trigger, bps. */
  megaFieldBps: number;
  /** Ceiling on a Mega-Pot payout, bps of the round's own pot; 0 = uncapped. */
  megaPayoutCapBps: number;
  /** One-time PlayerEscrow creation fee; seeds the Mega-Pot (decision D1). */
  accountOpenFeeLamports: bigint;
  /** `0`/`1` = launch 98/1/1 economics; `2` = four-way partial-loss. */
  economicsVersion: number;
}

/** `Round` as stored at PDA ["round", round_id_le]. */
export interface RoundData {
  roundId: bigint;
  state: RoundStateName;
  startTs: bigint;
  /** Mutated by anti-snipe extension only — the countdown target. */
  endTs: bigint;
  lockTs: bigint;
  lockSlot: bigint;
  settleTs: bigint;
  /** Escrowed total; also the exclusive ticket-space upper bound. */
  totalLamports: bigint;
  entryCount: number;
  entriesClosed: number;
  firstDepositor: string;
  singleDepositor: boolean;
  randomnessAccount: string;
  randomnessCommitSlot: bigint;
  randomnessSeedSlot: bigint;
  /** Authoritative once `settled` (I10); zero before. */
  winningTicket: bigint;
  /** Zero until claimed (ADR-2) — indexers read `winningTicket`, not this. */
  winner: string;
  winnerPayout: bigint;
  adminCut: bigint;
  megaCut: bigint;
  megaAwarded: bigint;
  vaultOwed: bigint;
  megaTriggered: boolean;
  prizeClaimed: boolean;
  vaultBump: number;
  bump: number;
  /** Settle-time obligation to the field: the 89% pool (Phase 11, I18). */
  refundPool: bigint;
  /** Running total actually paid out of `refundPool` (I20). */
  refundsPaid: bigint;
  /** Mega-Pot field share snapshotted at settle; 0 when no trigger. */
  megaFieldPool: bigint;
  /** Running total actually paid out of `megaFieldPool` (I20). */
  megaFieldPaid: bigint;
  /**
   * Who funded this round's two rent-exemptions at `open_round` — the one
   * legal `close_round` reclaim destination (Phase 12). The all-zero
   * legacy sentinel (`11111111111111111111111111111111`, the System
   * program id) marks rounds opened before Phase 12; those fall back to
   * the config admin via `rentReclaimDestination`.
   */
  rentPayer: string;
}

/** `PlayerEntry` as stored at PDA ["entry", round_id_le, entry_index_le]. */
export interface PlayerEntryAccountData {
  roundId: bigint;
  entryIndex: number;
  player: string;
  amountLamports: bigint;
  ticketStart: bigint;
  ticketEnd: bigint;
  depositTs: bigint;
  depositSlot: bigint;
  bump: number;
}

/**
 * `PlayerEscrow` as stored at PDA ["escrow", owner] (Phase 10).
 *
 * There is **no balance field**: spendable is always
 * `lamports − rent-exempt minimum` — prizes, refunds and rent rebates
 * arrive via `add_lamports` from instructions that know nothing about the
 * escrow, so any stored balance would desynchronise instantly.
 */
export interface PlayerEscrowData {
  /** Also the seed; the sole withdrawal authority. */
  owner: string;
  perRoundLamports: bigint;
  maxRounds: number;
  /** `0` ⇒ dormant. */
  roundsRemaining: number;
  /** `round_id + 1` after each auto-deposit (I17); never reset by re-fund. */
  nextEligibleRoundId: bigint;
  roundsFunded: bigint;
  lifetimeDeposited: bigint;
  lifetimeStaked: bigint;
  autoReinvest: boolean;
  bump: number;
}

/** `MegaPotVault` as stored at PDA ["mega_pot"]. */
export interface MegaPotVaultData {
  /** The authoritative spendable balance (I3) — never derive from lamports(). */
  accruedLamports: bigint;
  lifetimeContributed: bigint;
  lifetimeAwarded: bigint;
  triggerCount: bigint;
  lastTriggerRoundId: bigint;
  cycleIndex: bigint;
  bump: number;
}

function begin(
  data: Buffer,
  account: keyof typeof ACCOUNT_DISCRIMINATORS,
): BorshReader {
  const size = ACCOUNT_SIZES[account]!;
  if (data.length !== size) {
    throw new RangeError(
      `${account}: account data is ${data.length} bytes, expected exactly ${size} ` +
        `(allocated InitSpace size) — a layout change on-chain?`,
    );
  }
  const disc = data.subarray(0, 8).toString("hex");
  const want = ACCOUNT_DISCRIMINATORS[account]!;
  if (disc !== want) {
    throw new RangeError(
      `${account}: discriminator ${disc} does not match ${want} — wrong account type`,
    );
  }
  return new BorshReader(data.subarray(8));
}

/** Borsh `Option<Pubkey>`: 1-byte tag, then 32 key bytes when `Some`. */
function optionPubkey(r: BorshReader, what: string): string | null {
  const tag = r.u8(what);
  if (tag === 0) return null;
  if (tag !== 1) {
    throw new RangeError(`${what}: Option tag ${tag}, expected 0 or 1`);
  }
  return r.pubkey(`${what}.some`);
}

export function decodeGlobalConfig(data: Buffer): GlobalConfigData {
  const r = begin(data, "GlobalConfig");
  // Field order is declaration order — the reader is strictly sequential.
  const admin = r.pubkey("admin");
  const pendingAdmin = optionPubkey(r, "pendingAdmin");
  const treasuryAuthority = r.pubkey("treasuryAuthority");
  const oracleProgramId = r.pubkey("oracleProgramId");
  const oracleQueue = r.pubkey("oracleQueue");
  const feeBpsAdmin = r.u16Le("feeBpsAdmin");
  const feeBpsMega = r.u16Le("feeBpsMega");
  const winnerBps = r.u16Le("winnerBps");
  const megaAwardBps = r.u16Le("megaAwardBps");
  const megaTriggerModulus = r.u32Le("megaTriggerModulus");
  const maxEntriesPerRound = r.u32Le("maxEntriesPerRound");
  const roundDurationSecs = r.i64Le("roundDurationSecs");
  const maxRoundDurationSecs = r.i64Le("maxRoundDurationSecs");
  const antiSnipeWindowSecs = r.i64Le("antiSnipeWindowSecs");
  const antiSnipeExtensionSecs = r.i64Le("antiSnipeExtensionSecs");
  const claimDeadlineSecs = r.i64Le("claimDeadlineSecs");
  const minDepositLamports = r.u64Le("minDepositLamports");
  const antiSnipeMinDepositLamports = r.u64Le("antiSnipeMinDepositLamports");
  const keeperTipLamports = r.u64Le("keeperTipLamports");
  const randomnessRevealDeadlineSlots = r.u64Le("randomnessRevealDeadlineSlots");
  const activeRoundId = r.u64Le("activeRoundId");
  const nextRoundId = r.u64Le("nextRoundId");
  const providerTag = r.u8("oracleProvider");
  const oracleProvider = ORACLE_PROVIDERS[providerTag];
  if (oracleProvider === undefined) {
    throw new RangeError(`oracleProvider: ${providerTag}, expected 0, 1 or 2`);
  }
  const paused = r.bool("paused");
  const bump = r.u8("bump");
  // Phase 10 fields, immediately after `bump` — the pre-upgrade reserved
  // bytes were zero, so a deployed account reads 0n / 0n / false with no
  // migration (pinned by the zero-migration decoder test).
  const autoDepositWindowSecs = r.i64Le("autoDepositWindowSecs");
  const autoDepositTipLamports = r.u64Le("autoDepositTipLamports");
  const autoDepositEnabled = r.bool("autoDepositEnabled");
  // Phase 11 economics, immediately after the Phase 10 triple — same
  // zero-migration story: the deployed account's reserved bytes read as
  // refund 0 / field 0 / uncapped / fee 0 / version 0, which reproduce v1
  // arithmetic bit-for-bit (R6).
  const refundBps = r.u16Le("refundBps");
  const megaFieldBps = r.u16Le("megaFieldBps");
  const megaPayoutCapBps = r.u32Le("megaPayoutCapBps");
  const accountOpenFeeLamports = r.u64Le("accountOpenFeeLamports");
  const economicsVersion = r.u8("economicsVersion");
  return {
    admin,
    pendingAdmin,
    treasuryAuthority,
    oracleProgramId,
    oracleQueue,
    feeBpsAdmin,
    feeBpsMega,
    winnerBps,
    megaAwardBps,
    megaTriggerModulus,
    maxEntriesPerRound,
    roundDurationSecs,
    maxRoundDurationSecs,
    antiSnipeWindowSecs,
    antiSnipeExtensionSecs,
    claimDeadlineSecs,
    minDepositLamports,
    antiSnipeMinDepositLamports,
    keeperTipLamports,
    randomnessRevealDeadlineSlots,
    activeRoundId,
    nextRoundId,
    oracleProvider,
    paused,
    bump,
    autoDepositWindowSecs,
    autoDepositTipLamports,
    autoDepositEnabled,
    refundBps,
    megaFieldBps,
    megaPayoutCapBps,
    accountOpenFeeLamports,
    economicsVersion,
  };
}

export function decodeRound(data: Buffer): RoundData {
  const r = begin(data, "Round");
  // Field order is declaration order — the reader is strictly sequential.
  const roundId = r.u64Le("roundId");
  const stateIndex = r.u8("state");
  const state = ROUND_STATES[stateIndex];
  if (state === undefined) {
    throw new RangeError(`RoundState: ${stateIndex} is outside 0..4`);
  }
  const startTs = r.i64Le("startTs");
  const endTs = r.i64Le("endTs");
  const lockTs = r.i64Le("lockTs");
  const lockSlot = r.u64Le("lockSlot");
  const settleTs = r.i64Le("settleTs");
  const totalLamports = r.u64Le("totalLamports");
  const entryCount = r.u32Le("entryCount");
  const entriesClosed = r.u32Le("entriesClosed");
  const firstDepositor = r.pubkey("firstDepositor");
  const singleDepositor = r.bool("singleDepositor");
  const randomnessAccount = r.pubkey("randomnessAccount");
  const randomnessCommitSlot = r.u64Le("randomnessCommitSlot");
  const randomnessSeedSlot = r.u64Le("randomnessSeedSlot");
  const winningTicket = r.u64Le("winningTicket");
  const winner = r.pubkey("winner");
  const winnerPayout = r.u64Le("winnerPayout");
  const adminCut = r.u64Le("adminCut");
  const megaCut = r.u64Le("megaCut");
  const megaAwarded = r.u64Le("megaAwarded");
  const vaultOwed = r.u64Le("vaultOwed");
  const megaTriggered = r.bool("megaTriggered");
  const prizeClaimed = r.bool("prizeClaimed");
  const vaultBump = r.u8("vaultBump");
  const bump = r.u8("bump");
  // Phase 11 pool accounting, immediately after the bumps — zeroed
  // reserved bytes on an in-flight (v1-settled) round read as four 0n
  // fields and the round drains exactly as before the upgrade.
  const refundPool = r.u64Le("refundPool");
  const refundsPaid = r.u64Le("refundsPaid");
  const megaFieldPool = r.u64Le("megaFieldPool");
  const megaFieldPaid = r.u64Le("megaFieldPaid");
  // Phase 12: the trailing 32 bytes, repurposed in place from padding to
  // the rent payer — a clean append after `megaFieldPaid`, no offset
  // moves. A zeroed tail (every pre-Phase-12 round) decodes as the System
  // program address, the legacy sentinel.
  const rentPayer = r.pubkey("rentPayer");
  return {
    roundId,
    state,
    startTs,
    endTs,
    lockTs,
    lockSlot,
    settleTs,
    totalLamports,
    entryCount,
    entriesClosed,
    firstDepositor,
    singleDepositor,
    randomnessAccount,
    randomnessCommitSlot,
    randomnessSeedSlot,
    winningTicket,
    winner,
    winnerPayout,
    adminCut,
    megaCut,
    megaAwarded,
    vaultOwed,
    megaTriggered,
    prizeClaimed,
    vaultBump,
    bump,
    refundPool,
    refundsPaid,
    megaFieldPool,
    megaFieldPaid,
    rentPayer,
  };
}

export function decodePlayerEntry(data: Buffer): PlayerEntryAccountData {
  const r = begin(data, "PlayerEntry");
  return {
    roundId: r.u64Le("roundId"),
    entryIndex: r.u32Le("entryIndex"),
    player: r.pubkey("player"),
    amountLamports: r.u64Le("amount"),
    ticketStart: r.u64Le("ticketStart"),
    ticketEnd: r.u64Le("ticketEnd"),
    depositTs: r.i64Le("depositTs"),
    depositSlot: r.u64Le("depositSlot"),
    bump: r.u8("bump"),
  };
}

export function decodePlayerEscrow(data: Buffer): PlayerEscrowData {
  const r = begin(data, "PlayerEscrow");
  return {
    owner: r.pubkey("owner"),
    perRoundLamports: r.u64Le("perRoundLamports"),
    maxRounds: r.u32Le("maxRounds"),
    roundsRemaining: r.u32Le("roundsRemaining"),
    nextEligibleRoundId: r.u64Le("nextEligibleRoundId"),
    roundsFunded: r.u64Le("roundsFunded"),
    lifetimeDeposited: r.u64Le("lifetimeDeposited"),
    lifetimeStaked: r.u64Le("lifetimeStaked"),
    autoReinvest: r.bool("autoReinvest"),
    bump: r.u8("bump"),
  };
}

export function decodeMegaPotVault(data: Buffer): MegaPotVaultData {
  const r = begin(data, "MegaPotVault");
  return {
    accruedLamports: r.u64Le("accruedLamports"),
    lifetimeContributed: r.u64Le("lifetimeContributed"),
    lifetimeAwarded: r.u64Le("lifetimeAwarded"),
    triggerCount: r.u64Le("triggerCount"),
    lastTriggerRoundId: r.u64Le("lastTriggerRoundId"),
    cycleIndex: r.u64Le("cycleIndex"),
    bump: r.u8("bump"),
  };
}

/** The self-hosted randomness chain singleton at ["entropy_chain"]. */
export interface EntropyChainData {
  /** sha256 of the next seed to reveal, hex. */
  commit: string;
  remaining: bigint;
  /** `ENTROPY_NONE` when no round is in flight. */
  pendingRound: bigint;
  targetSlot: bigint;
  requestSlot: bigint;
  value: string;
  /** `ENTROPY_NONE` once the value has been settled. */
  valueRound: bigint;
  valueSlot: bigint;
  revealedCount: bigint;
  bump: number;
}

export function decodeEntropyChain(data: Buffer): EntropyChainData {
  const r = begin(data, "EntropyChain");
  const hex = (b: Uint8Array) => Buffer.from(b).toString("hex");
  return {
    commit: hex(r.fixedBytes(32, "commit")),
    remaining: r.u64Le("remaining"),
    pendingRound: r.u64Le("pendingRound"),
    targetSlot: r.u64Le("targetSlot"),
    requestSlot: r.u64Le("requestSlot"),
    value: hex(r.fixedBytes(32, "value")),
    valueRound: r.u64Le("valueRound"),
    valueSlot: r.u64Le("valueSlot"),
    revealedCount: r.u64Le("revealedCount"),
    bump: r.u8("bump"),
  };
}
