/**
 * The canonical program IDL, generated by `anchor build` from the program
 * source and committed here so consumers never depend on build output
 * (target/idl is git-ignored). Regenerate deliberately:
 * `anchor build && cp target/idl/orbit_jackpot.json packages/sdk/idl/`.
 *
 * The decoders and event subscriptions in this SDK deliberately do NOT use
 * the IDL at runtime (raw offset-pinned decodes, committed discriminators)
 * — it is exported for tooling, explorers, and any future anchor `Program`
 * usage.
 */

import type { Idl } from "@coral-xyz/anchor";
import raw from "../idl/orbit_jackpot.json";

/** The orbit_jackpot IDL; `metadata.address` matches `pda.PROGRAM_ID`. */
export const ORBIT_JACKPOT_IDL = raw as unknown as Idl;
